### ISSUE TITLE
Panel missing assets

### ISSUE THREAD

**Issue by marvin52** [feedcast/core#15]
![screenshot 5](https://user-images.githubusercontent.com/2734828/30307848-38bfff86-9779-11e7-9444-2579393cc700.png)

**Comment by marceloboeira** [comment]
I've tested here with http/https, different browsers.. could not simulate the problem. can you try to send me the steps to reproducee it?

**Comment by marvin52** [comment]
yes, i basically copy the url and paste on chrome

**Comment by marceloboeira** [comment]
Working just fine here with chrome. I will close it while we don't have how to simulate it.
